name: gg_tree_expressions
description: Assign expressions to gg_tree properties and connect rule books with ease
version: 0.0.1
repository: https://github.com/ggsuite/gg_tree_expressions.git

environment:
  sdk: ">=3.11.4 <4.0.0"

dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2
